using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Tarinoi.Editor.Codegen
{
    /// <summary>
    /// Renders a <see cref="CodegenModel"/> as C# source.
    /// </summary>
    /// <remarks>
    /// Output is deterministic — collections and members are emitted in sorted order, and
    /// the header carries no timestamp — so regenerating without content changes produces
    /// no diff. That matters because these files are committed.
    /// </remarks>
    public static class CodeEmitter
    {
        public const string Namespace = "Tarinoi.Generated";

        public const string FunctionsFile = "TarinoiFunctions.g.cs";
        public const string VariablesFile = "TarinoiVariables.g.cs";
        public const string ListsFile = "TarinoiLists.g.cs";
        public const string EntitiesFile = "TarinoiEntities.g.cs";

        /// <summary>Named after the namespace, so the assembly and the code agree.</summary>
        public const string AsmdefFile = Namespace + ".asmdef";

        static string Header(string projectId) =>
            "// <auto-generated>\n"
            + "//     Generated by Tarinoi from the synced content of project "
            + $"'{projectId}'.\n"
            + "//     Do not edit: regenerating overwrites this file. Implement your\n"
            + "//     bindings by deriving from these classes in your own files.\n"
            + "// </auto-generated>\n\n";

        // -------------------------------------------------------------------------
        // Assembly definition
        // -------------------------------------------------------------------------

        /// <summary>
        /// Emits the assembly definition that puts the generated code in its own assembly.
        /// </summary>
        /// <remarks>
        /// Written only when the project asks for it. A project that keeps its code in the
        /// predefined <c>Assembly-CSharp</c> wants no asmdef here at all — one would move
        /// the generated types out of reach of everything already written against them.
        /// A project that uses asmdefs cannot see <c>Assembly-CSharp</c> and so needs this.
        /// <para>
        /// <c>Newtonsoft.Json.dll</c> is listed because authored payloads surface as
        /// <c>JObject</c>, and <c>autoReferenced</c> stays on so ordinary game code picks
        /// this up without listing it.
        /// </para>
        /// </remarks>
        public static string Asmdef() =>
            "{\n"
            + $"    \"name\": \"{Namespace}\",\n"
            + $"    \"rootNamespace\": \"{Namespace}\",\n"
            + "    \"references\": [\n"
            + "        \"Tarinoi.Runtime\"\n"
            + "    ],\n"
            + "    \"includePlatforms\": [],\n"
            + "    \"excludePlatforms\": [],\n"
            + "    \"allowUnsafeCode\": false,\n"
            + "    \"overrideReferences\": true,\n"
            + "    \"precompiledReferences\": [\n"
            + "        \"Newtonsoft.Json.dll\"\n"
            + "    ],\n"
            + "    \"autoReferenced\": true,\n"
            + "    \"defineConstraints\": [],\n"
            + "    \"versionDefines\": [],\n"
            + "    \"noEngineReferences\": false\n"
            + "}\n";

        // -------------------------------------------------------------------------
        // Functions
        // -------------------------------------------------------------------------

        /// <summary>
        /// Emits one abstract class per function collection.
        /// </summary>
        /// <remarks>
        /// Each class implements <c>TryInvoke</c> as a switch rather than relying on
        /// reflection, so dispatch survives IL2CPP's managed code stripping. Unimplemented
        /// functions log and return a default instead of throwing — an authoring mistake
        /// should not take down a running game.
        /// </remarks>
        public static string Functions(CodegenModel model, string projectId)
        {
            var w = new Writer();
            w.Line(Header(projectId).TrimEnd('\n'));
            w.Line();
            w.Line("using Tarinoi;");
            w.Line("using Tarinoi.Bindings;");
            w.Line();
            w.Line($"namespace {Namespace}");
            w.Open();

            if (model.Functions.Count == 0)
            {
                w.Line("// No function collections have been synced yet.");
            }

            var first = true;
            foreach (var collection in model.Functions)
            {
                if (!first)
                {
                    w.Line();
                }

                first = false;
                EmitFunctionClass(w, collection.Key, collection.Value);
            }

            w.Close();
            return w.ToString();
        }

        static void EmitFunctionClass(Writer w, string collection, List<FunctionDecl> functions)
        {
            var className = CodeNames.CollectionClass(collection, "Functions");

            w.Doc($"Functions the author can call as <c>Fn.{collection}.*</c>.");
            w.Doc("Derive from this and override the ones your game implements.", "remarks");
            w.Line($"public abstract partial class {className} : ITarinoiFunctions");
            w.Open();

            var ordered = functions.OrderBy(f => f.Name, StringComparer.Ordinal).ToList();

            foreach (var fn in ordered)
            {
                EmitFunctionStub(w, className, fn);
                w.Line();
            }

            EmitHasFunction(w, ordered);
            w.Line();
            EmitTryInvoke(w, className, ordered);

            w.Close();
        }

        static void EmitFunctionStub(Writer w, string className, FunctionDecl fn)
        {
            var signature = $"{fn.Name}({string.Join(", ", fn.Args)}) -> "
                            + (string.IsNullOrEmpty(fn.Returns) ? "void" : fn.Returns);
            w.Doc(signature);
            if (!string.IsNullOrEmpty(fn.Effect))
            {
                w.Doc($"Effect: {fn.Effect}", "remarks");
            }

            var returnType = CodeTypes.ForReturn(fn.Returns);
            var parameters = string.Join(", ", fn.Args.Select(a => $"object {CodeNames.Parameter(a)}"));

            w.Line($"public virtual {returnType} {CodeNames.Member(fn.Name)}({parameters})");
            w.Open();
            w.Line($"TarinoiLog.Error(\"{className}.{CodeNames.Member(fn.Name)} is not implemented. \"");
            w.Line("    + \"Override it in your bindings class.\");");

            var defaultLiteral = CodeTypes.DefaultReturnLiteral(fn.Returns);
            if (defaultLiteral.Length > 0)
            {
                w.Line($"return {defaultLiteral};");
            }

            w.Close();
        }

        static void EmitHasFunction(Writer w, List<FunctionDecl> functions)
        {
            w.Line("public bool HasFunction(string name)");
            w.Open();
            w.Line("switch (name)");
            w.Open();

            foreach (var fn in functions)
            {
                w.Line($"case {CodeNames.StringLiteral(fn.Name)}:");
            }

            if (functions.Count > 0)
            {
                w.Line("    return true;");
            }

            w.Line("default:");
            w.Line("    return false;");
            w.Close();
            w.Close();
        }

        static void EmitTryInvoke(Writer w, string className, List<FunctionDecl> functions)
        {
            w.Doc("Dispatches an authored call. A switch rather than reflection, so this "
                  + "keeps working under IL2CPP's managed code stripping.", "remarks");
            w.Line("public bool TryInvoke(string name, object[] args, out object result)");
            w.Open();
            w.Line("result = null;");
            w.Line("var count = args?.Length ?? 0;");
            w.Line();
            w.Line("switch (name)");
            w.Open();

            foreach (var fn in functions)
            {
                var member = CodeNames.Member(fn.Name);
                var arity = fn.Args.Count;

                w.Line($"case {CodeNames.StringLiteral(fn.Name)}:");
                w.Indent();

                if (arity > 0)
                {
                    // Arity is checked rather than assumed: the synced declaration can
                    // change after this file was generated.
                    w.Line($"if (count != {arity})");
                    w.Open();
                    w.Line($"TarinoiLog.Error(\"{className}.{member} takes {arity} argument(s) \"");
                    w.Line("    + $\"but the authored call passed {count}. Regenerate your bindings.\");");
                    w.Line("return true;");
                    w.Close();
                }

                var callArgs = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"args[{i}]"));
                if (CodeTypes.IsVoid(fn.Returns))
                {
                    w.Line($"{member}({callArgs});");
                }
                else
                {
                    w.Line($"result = {member}({callArgs});");
                }

                w.Line("return true;");
                w.Outdent();
            }

            w.Line("default:");
            w.Line("    return false;");
            w.Close();
            w.Close();
        }

        // -------------------------------------------------------------------------
        // Variables
        // -------------------------------------------------------------------------

        /// <summary>
        /// Emits one class per variable collection, with a typed field per variable and
        /// name-based accessors the dispatcher uses.
        /// </summary>
        public static string Variables(CodegenModel model, string projectId)
        {
            var w = new Writer();
            w.Line(Header(projectId).TrimEnd('\n'));
            w.Line();
            w.Line("using Tarinoi.Bindings;");
            w.Line();
            w.Line($"namespace {Namespace}");
            w.Open();

            if (model.Variables.Count == 0)
            {
                w.Line("// No variable collections have been synced yet.");
            }

            var first = true;
            foreach (var collection in model.Variables)
            {
                if (!first)
                {
                    w.Line();
                }

                first = false;
                EmitVariableClass(w, collection.Key, collection.Value);
            }

            w.Close();
            return w.ToString();
        }

        static void EmitVariableClass(Writer w, string collection, List<VariableDecl> variables)
        {
            var className = CodeNames.CollectionClass(collection, "Variables");
            var ordered = variables.OrderBy(v => v.Name, StringComparer.Ordinal).ToList();

            w.Doc($"State the author reads and writes as <c>Var.{collection}.*</c>.");
            w.Doc("Fields hold the values directly; assign to them from your game code, or "
                  + "derive and add behaviour.", "remarks");
            w.Line($"public partial class {className} : ITarinoiVariables");
            w.Open();

            foreach (var v in ordered)
            {
                w.Doc($"<c>Var.{collection}.{v.Name}</c>");
                w.Line($"public {CodeTypes.ForData(v.DataType)} {CodeNames.Member(v.Name)} = "
                       + $"{CodeTypes.DefaultValueLiteral(v.DataType, v.DefaultValue)};");
                w.Line();
            }

            // Virtual, like the generated functions: a game that keeps its state in a
            // savegame or a blackboard overrides these and calls back to base for the
            // rest, instead of giving up the typed fields and starting from the interface.
            w.Line("public virtual object GetVariable(string name)");
            w.Open();
            w.Line("switch (name)");
            w.Open();
            foreach (var v in ordered)
            {
                w.Line($"case {CodeNames.StringLiteral(v.Name)}: return {CodeNames.Member(v.Name)};");
            }

            w.Line("default:");
            w.Line("    TarinoiLog.Warn($\"" + className
                   + " has no variable '{name}'. Regenerate your bindings.\");");
            w.Line("    return null;");
            w.Close();
            w.Close();
            w.Line();

            w.Line("public virtual void SetVariable(string name, object value)");
            w.Open();
            w.Line("switch (name)");
            w.Open();
            foreach (var v in ordered)
            {
                w.Line($"case {CodeNames.StringLiteral(v.Name)}:");
                w.Line($"    {CodeNames.Member(v.Name)} = {ConvertExpression(v.DataType)};");
                w.Line("    return;");
            }

            w.Line("default:");
            w.Line("    TarinoiLog.Warn($\"" + className
                   + " has no variable '{name}'. Regenerate your bindings.\");");
            w.Line("    return;");
            w.Close();
            w.Close();

            w.Close();
        }

        /// <summary>
        /// Values arrive boxed and loosely typed, so assignment goes through a converter
        /// rather than a cast that would throw inside game code.
        /// </summary>
        static string ConvertExpression(string dataType)
        {
            switch (CodeTypes.ForData(dataType))
            {
                case "bool": return "ValueConvert.ToBool(value)";
                case "double": return "ValueConvert.ToDouble(value)";
                case "string": return "ValueConvert.ToText(value)";
                default: return "ValueConvert.Unwrap(value)";
            }
        }

        // -------------------------------------------------------------------------
        // Lists and entities
        // -------------------------------------------------------------------------

        /// <summary>Emits option-key constants, so authored keys can be referred to safely.</summary>
        public static string Lists(CodegenModel model, string projectId)
        {
            var w = new Writer();
            w.Line(Header(projectId).TrimEnd('\n'));
            w.Line();
            w.Line($"namespace {Namespace}");
            w.Open();

            if (model.Lists.Count == 0)
            {
                w.Line("// No option lists have been synced yet.");
            }

            var first = true;
            foreach (var collection in model.Lists)
            {
                if (!first)
                {
                    w.Line();
                }

                first = false;

                w.Doc($"Option keys for the lists in <c>Ls.{collection.Key}.*</c>.");
                w.Line($"public static class {CodeNames.CollectionClass(collection.Key, "Lists")}");
                w.Open();

                var firstList = true;
                foreach (var list in collection.Value.OrderBy(l => l.Identifier, StringComparer.Ordinal))
                {
                    if (!firstList)
                    {
                        w.Line();
                    }

                    firstList = false;

                    w.Doc($"<c>Ls.{collection.Key}.{list.Identifier}.*</c>");
                    w.Line($"public static class {CodeNames.ToPascal(list.Identifier)}");
                    w.Open();
                    foreach (var key in list.OptionKeys.OrderBy(k => k, StringComparer.Ordinal))
                    {
                        w.Line($"public const string {CodeNames.Member(key)} = "
                               + $"{CodeNames.StringLiteral(key)};");
                    }

                    w.Close();
                }

                w.Close();
            }

            w.Close();
            return w.ToString();
        }

        /// <summary>Emits identifier constants for entities that can take part in dialogue.</summary>
        public static string Entities(CodegenModel model, string projectId)
        {
            var w = new Writer();
            w.Line(Header(projectId).TrimEnd('\n'));
            w.Line();
            w.Line($"namespace {Namespace}");
            w.Open();

            if (model.Entities.Count == 0)
            {
                w.Line("// No dialogue-capable entities have been synced yet.");
            }

            var first = true;
            foreach (var collection in model.Entities)
            {
                if (!first)
                {
                    w.Line();
                }

                first = false;

                w.Doc($"Entities available as <c>Ent.{collection.Key}.*</c>.");
                w.Line($"public static class {CodeNames.CollectionClass(collection.Key, "Entities")}");
                w.Open();
                foreach (var entity in collection.Value.OrderBy(e => e.Identifier, StringComparer.Ordinal))
                {
                    w.Line($"public const string {CodeNames.Member(entity.Identifier)} = "
                           + $"{CodeNames.StringLiteral(entity.Identifier)};");
                }

                w.Close();
            }

            w.Close();
            return w.ToString();
        }

        // -------------------------------------------------------------------------

        /// <summary>Minimal indenting source writer.</summary>
        sealed class Writer
        {
            readonly StringBuilder _builder = new StringBuilder();
            int _depth;

            public void Indent() => _depth++;
            public void Outdent() => _depth = Math.Max(0, _depth - 1);

            public void Open()
            {
                Line("{");
                Indent();
            }

            public void Close()
            {
                Outdent();
                Line("}");
            }

            public void Doc(string text, string tag = "summary")
            {
                Line($"/// <{tag}>{text}</{tag}>");
            }

            public void Line(string text = "")
            {
                if (text.Length == 0)
                {
                    _builder.Append('\n');
                    return;
                }

                foreach (var part in text.Split('\n'))
                {
                    _builder.Append(new string(' ', _depth * 4)).Append(part).Append('\n');
                }
            }

            public override string ToString() => _builder.ToString();
        }
    }
}
